---
title: "Modélisation logistique de l'accès au crédit et à l'épargne"
author: "Mouhamet Seck"
date: "30 mai 2025"
output: 
  beamer_presentation:
    theme: "Madrid"
    colortheme: "dolphin"
    fonttheme: "structurebold"
    highlight: tango
    latex_engine: xelatex
header-includes:
  - \usepackage{fontspec}
  - \setmainfont{Arial}
---

## Introduction

### Contexte et objectif

- Analyse des déterminants de l’accès au crédit et à l’épargne au Sénégal.
- Utilisation des données de l’EHCVM 2018.
- Modélisation par régression logistique binaire :
  - Accès au crédit (`a_credit`)
  - Accès à l’épargne (`a_epargne`)

## Pourquoi ce sujet est-il important ?

- L’accès aux services financiers est considéré comme un facteur de progrès pour sept des 17 Objectifs de développement durable..
- Accès au crédit : moteur de l’entrepreneuriat et de la résilience économique.
- Accès à l’épargne : facteur de sécurité et d’investissement.
- Au Sénégal, de fortes inégalités persistent selon le sexe, l’éducation et le milieu de résidence.

## Données utilisées

### Source et préparation

- Base de données : Enquête Harmonisée sur les Conditions de Vie des Ménages (EHCVM), édition 2018.
- Fusion de modules : sociodémographique, emploi, éducation, revenus, logement, transferts, épargne-crédit.
- Nettoyage, recodage, gestion des valeurs manquantes.
- Variables finales retenues : âge, sexe, niveau d’étude, statut matrimonial, téléphone, religion, milieu, région, revenu hors emploi, transfert.

## Méthodologie

### Approche statistique

- Deux modèles de régression logistique binaires :
  - Prédiction de `a_credit` et `a_epargne`
- Variables explicatives : 
  - Tranche d'âge, sexe, niveau d'étude, statut matrimonial, téléphone, religion, milieu, région, revenu hors emploi, transfert.
- Évaluation des effets via les odds ratios et significativité statistique.

## Résultats : Accès au Crédit

### Principaux facteurs influençant l'accès au crédit

- **Effets positifs** :
  - Âge entre 25–64 ans
  - Niveau d’éducation élevé (secondaire et supérieur)
  - Possession d’un téléphone
  - Statut matrimonial (marié(e))
  - Revenus hors emploi
  - Certaines régions (Fatick, Kolda, Kaffrine)

- **Effets négatifs** :
  - Être un homme
  - Être célibataire
  - Milieu urbain (faiblement significatif)
  - Régions défavorisées (Saint-Louis, Louga, Ziguinchor)

## Résultats : Accès à l'Épargne

### Principaux facteurs influençant l'accès à l'épargne

- **Effets positifs** :
  - Âge croissant jusqu’à 64 ans
  - Sexe masculin
  - Niveau d’éducation très élevé (supérieur)
  - Possession d’un téléphone (effet très fort)
  - Milieu urbain
  - Revenus hors emploi et transferts
  - Région de Ziguinchor

- **Effets négatifs** :
  - Être célibataire
  - Zones rurales ou enclavées (Matam, Saint-Louis, Kolda, Thiès, Fatick, Sédhiou)

## Conclusion et Recommandations

### Principales conclusions

- L’éducation joue un rôle central dans l’inclusion financière.
- Disparités géographiques importantes.
- Le téléphone mobile est un levier essentiel pour l’inclusion financière.
- Genre : les femmes ont meilleur accès au crédit, mais les hommes sont plus inclus dans l’épargne.

### Recommandations

- Programmes ciblés :
  - Pour les jeunes et les personnes peu instruites.
  - Dans les zones rurales.
  - Promotion de l’épargne mobile et alphabétisation financière.
  - Renforcement des mécanismes de crédit rural.

## Profils types

### Profil type d’un individu ayant accès :

#### Au crédit :
- Femme âgée de 35 à 54 ans  
- Niveau d’éducation secondaire ou supérieur  
- Mariée  
- Revenu hors emploi  
- Téléphone  
- Habitant à Kolda ou Fatick

#### À l’épargne :
- Homme âgé de 35 à 54 ans  
- Niveau d’éducation supérieur  
- Milieu urbain  
- Téléphone  
- Revenus hors emploi et/ou transferts


## Remerciements

\vspace{2cm}

\begin{center}
\Huge \textbf{Merci de votre attention !}
\end{center}

\vspace{1cm}