---
title: "Untitled"
author: "Moustapha Ndiaye"
date: "`r Sys.Date()`"
output: 
  beamer_presentation:
    slide_level: 2
---
```{r, echo=FALSE}
library(tidyverse)
library(FactoMineR)
library(factoextra)

# Charger le script qui crée base_final_imputed
source("Untitled11.R")
```
## 1. Problèmes de santé

```{r, echo=FALSE}
tab_probleme <- table(base_final_imputed$probleme_sante)
barplot(tab_probleme,
        main = "Problèmes de santé",
        col = "steelblue",
        names.arg = c("Aucun", "Oui"))
```

## 2. Consultation médicale

```{r, echo=FALSE}
malades <- base_final_imputed %>% filter(probleme_sante == 1)
tab_consulte <- table(malades$a_consulte)
barplot(tab_consulte,
        main = "Consultation médicale",
        col = "darkred",
        names.arg = c("Non", "Oui"))
```

## 3. Types de problèmes de santé

```{r, echo=FALSE}
tab_type <- table(malades$type_probleme)
barplot(tab_type,
        las = 2,
        col = "orange",
        main = "Types de problèmes de santé")
```

## 4. Analyse en Composantes Principales (ACP) - Variables santé

```{r, echo=FALSE}
vars_sante <- c("probleme_sante", "type_probleme", "a_consulte",
                "s03q04", "s03q05", "s03q06", "type_structure",
                "s03q08", "satisfaction_soins", "s03q39", "s03q40")

df_acp <- base_final_imputed %>%
  select(all_of(vars_sante)) %>%
  drop_na() %>%
  mutate(across(everything(), as.numeric))

set.seed(123)
df_sample <- df_acp[sample(nrow(df_acp), min(1000, nrow(df_acp))), ]
res_acp <- PCA(df_sample, scale.unit = TRUE, graph = FALSE)

fviz_pca_var(res_acp,
             col.var = "contrib",
             repel = TRUE,
             title = "ACP - Variables Santé")
```

## 5. Corrélation santé et variables socio-économiques

```{r, echo=FALSE}
vars_socioeco <- c("s01q01", "s01q04a", "s01q07", "s02q29", "s04q43",
                   "s04q57", "s11q01", "s11q02", "s11q04", "s11q05", "s11q32")

df_cor <- base_final_imputed %>%
  select(all_of(c(vars_sante, vars_socioeco))) %>%
  drop_na() %>%
  mutate(across(everything(), as.numeric))

cor_matrix <- cor(df_cor[, vars_sante], df_cor[, vars_socioeco])

heatmap(cor_matrix,
        main = "Corrélation Santé / Variables Socio-Économiques",
        col = topo.colors(10))
```
